// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGLPasQ2Z2Zo_Sca9BlIQgA2C8kCAdzCk',
    appId: '1:554938370328:web:948806232ed591899d766d',
    messagingSenderId: '554938370328',
    projectId: 'sport0zero',
    authDomain: 'sport0zero.firebaseapp.com',
    storageBucket: 'sport0zero.firebasestorage.app',
    measurementId: 'G-NZ8E9GY1S5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7NoAUvv51Dy9BxdxFjGZLKtEST6nH77k',
    appId: '1:554938370328:android:7e0469797f2047309d766d',
    messagingSenderId: '554938370328',
    projectId: 'sport0zero',
    storageBucket: 'sport0zero.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfsmmM0sW4HfViehtM3VC5AWFYQdrj0ZY',
    appId: '1:554938370328:ios:5c5af804f4547de49d766d',
    messagingSenderId: '554938370328',
    projectId: 'sport0zero',
    storageBucket: 'sport0zero.firebasestorage.app',
    iosBundleId: 'com.sport0zero.sport0zero',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfsmmM0sW4HfViehtM3VC5AWFYQdrj0ZY',
    appId: '1:554938370328:ios:5c5af804f4547de49d766d',
    messagingSenderId: '554938370328',
    projectId: 'sport0zero',
    storageBucket: 'sport0zero.firebasestorage.app',
    iosBundleId: 'com.sport0zero.sport0zero',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGLPasQ2Z2Zo_Sca9BlIQgA2C8kCAdzCk',
    appId: '1:554938370328:web:49cb75b99c7f6c2e9d766d',
    messagingSenderId: '554938370328',
    projectId: 'sport0zero',
    authDomain: 'sport0zero.firebaseapp.com',
    storageBucket: 'sport0zero.firebasestorage.app',
    measurementId: 'G-QEQL742NT1',
  );
}
